[profile.default]
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]
optimizer = true
optimizer_runs = 500000
solc_version = '0.8.21'
libs = ['node_modules', 'lib']

src = 'contracts'
test = 'test/foundry'
out = 'artifacts/forge'
cache_path='cache/forge'

rpc_endpoints = {mainnet = "${RPC_ENDPOINT_MAINNET}", goerli = "${RPC_ENDPOINT_GOERLI}", optimism_goerli = "${RPC_ENDPOINT_OPTIMISM_GOERLI}", base_goerli = "${RPC_ENDPOINT_BASE_GOERLI}" }
